//
// Created by mabartos on 10/29/19.
//

#ifndef ISA_CLIENT_H
#define ISA_CLIENT_H

#include "string"

using namespace std;

/**
 * Client side of Http Dashboard
 */
class Client {
private:
    string host;
    int port;
    string request;

    /**
    * Parse Response from server
    * This method prints Response Header to STDOUT and HTTP Response body to STDERR
    * @param buffer Whole response
    */
    void printResponse(char *buffer);

public:
    /**
     * Client Constructor
     * @param host Hostname, or IPv4
     * @param port Port, where server listen to requests
     * @param request Is automatically generated by ClientParser
     */
    Client(string host, int port, string request);

    ~Client() = default;

    /**
     * Main method of client, which run the client
     */
    void run();

    //Getters
    string getHost();

    int getPort();

    string getRequest();
};


#endif //ISA_CLIENT_H
